version: '3'

services:
    php:
        container_name: laravel-php
        build: .docker/php
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www:cached

    nginx:
        container_name: laravel-nginx
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    mail:
        container_name: laravel-mail
        image: axllent/mailpit:latest
        ports:
            - "8025:8025"
            - "1025:1025"

    redis:
        container_name: laravel-redis
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - .docker/redis/data:/data
        ports:
            - "6379:6379"

    db:
        container_name: laravel-db
        image: postgres:16
        #        ports:
        #            - "5432:5432"
        volumes:
            - .docker/db/data:/var/lib/postgresql/data
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=laravel_11
